//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCIClasificadoMvc4App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClasificadoEntities : DbContext
    {
        public ClasificadoEntities()
            : base("name=ClasificadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clasificado> Clasificado { get; set; }
        public DbSet<ClasificadoEstado> ClasificadoEstado { get; set; }
        public DbSet<ClasificadoView> ClasificadoView { get; set; }
    }
}
