//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCIClasificadoMvc4App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clasificado
    {
        public long clasificadoId { get; set; }
        public string clasificadoTexto { get; set; }
        public System.DateTime publicacionFI { get; set; }
        public System.DateTime publicacionFF { get; set; }
        public int estadoId { get; set; }
    
        public virtual ClasificadoEstado ClasificadoEstado { get; set; }
    }
}
